config/routes.rb
Mymystery::Application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_for :clients
  resources :clients
  resources :cars
  resources :deals
  resources :requests
  resources :sales
  root :to => "cars#index"
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :client_id, :date, :number, :user_id, :value, :vin
  validates :date, :presence => {:message => 'Date cannot be blank, Deal not saved'}
  validates :value, :presence => {:message => 'Value cannot be blank, Deal not saved'}
  after_save :set_car_status
  #before_save :check_car_status
  def set_car_status
    if Car.where(:vin => self.vin).first
      Car.where(:vin => self.vin).first.update_attributes(:status => 0)
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :authenticate_admin!, :only => [:destroy]
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<ul>
  <% @deal.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<%= form_for @deal, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'text_field', :value => Time.now.strftime("%d.%m.%y") %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :value, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :client_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :client_id, :class => 'number_field', :value => 1 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vin, :class => 'text_field', :value => '1AUKSA37864KS000000 ' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field', :value => current_user.id if user_signed_in? %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :number, :class => 'number_field', :value => 1 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deals_path, :class => 'btn' %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/index.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:client_id) %></th>
      <th><%= model_class.human_attribute_name(:vin) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= link_to deal.id, deal_path(deal) %></td>
        <td><%= deal.date %></td>
        <td><%= deal.value %></td>
        <td><%= deal.client_id %></td>
        <td><%= deal.vin %></td>
        <td><%= deal.user_id %></td>
        <td><%= deal.number %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_deal_path(deal), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      deal_path(deal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_deal_path,
            :class => 'btn btn-primary' %>

app/views/deals/new.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/show.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @deal.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @deal.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:client_id) %>:</strong></dt>
  <dd><%= @deal.client_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vin) %>:</strong></dt>
  <dd><%= @deal.vin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @deal.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @deal.number %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              deals_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_deal_path(@deal), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              deal_path(@deal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>