config/routes.rb
Mymystery::Application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_for :clients
  resources :clients
  resources :cars
  resources :deals
  resources :requests
  resources :sales
  root :to => "cars#index"
end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :brand, :color, :model, :modification, :package_bundle, :status, :vin
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :authenticate_admin!, :only => [:destroy]
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :vin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vin, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :brand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brand, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :modification, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :modification, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :package_bundle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :package_bundle, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :color, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :color, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :status, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:vin) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:modification) %></th>
      <th><%= model_class.human_attribute_name(:package_bundle) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.vin %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.modification %></td>
        <td><%= car.package_bundle %></td>
        <td><%= car.color %></td>
        <td><%= car.status==1? 'В наличии' : 'Продана' %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:vin) %>:</strong></dt>
  <dd><%= @car.vin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @car.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @car.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modification) %>:</strong></dt>
  <dd><%= @car.modification %></dd>
  <dt><strong><%= model_class.human_attribute_name(:package_bundle) %>:</strong></dt>
  <dd><%= @car.package_bundle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @car.color %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @car.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>