config/routes.rb
Mymystery::Application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_for :clients
  resources :clients
  resources :cars
  resources :deals
  resources :requests
  resources :sales
  root :to => "cars#index"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :brand, :color, :model, :modification, :name, :package_bundle, :patronymic, :phone, :state, :surname
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_filter :authenticate_admin!, :only => [:destroy]
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :surname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :class => 'text_field', :value => current_client.surname if client_signed_in? %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :value => current_client.name if client_signed_in? %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :patronymic, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :patronymic, :class => 'text_field', :value => current_client.patronymic if client_signed_in? %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field', :value => current_client.phone if client_signed_in? %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :brand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brand, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :modification, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :modification, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :package_bundle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :package_bundle, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :color, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :color, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:patronymic) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:modification) %></th>
      <th><%= model_class.human_attribute_name(:package_bundle) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.surname %></td>
        <td><%= sale.name %></td>
        <td><%= sale.patronymic %></td>
        <td><%= sale.phone %></td>
        <td><%= sale.brand %></td>
        <td><%= sale.model %></td>
        <td><%= sale.modification %></td>
        <td><%= sale.package_bundle %></td>
        <td><%= sale.color %></td>
        <td><%= sale.state %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @sale.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sale.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:patronymic) %>:</strong></dt>
  <dd><%= @sale.patronymic %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @sale.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @sale.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @sale.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modification) %>:</strong></dt>
  <dd><%= @sale.modification %></dd>
  <dt><strong><%= model_class.human_attribute_name(:package_bundle) %>:</strong></dt>
  <dd><%= @sale.package_bundle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @sale.color %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @sale.state %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>