config/routes.rb
Mymystery::Application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_for :clients
  resources :clients
  resources :cars
  resources :deals
  resources :requests
  resources :sales
  root :to => "cars#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Avtoprestizh" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Avtoprestizh</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if client_signed_in?%>
                <li><%= link_to "Sign out", destroy_session_path(:client), :method => :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_session_path(:client) %></li>
                <li><%= link_to "Sign up", new_registration_path(:client) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Categories</li>
              <% if user_signed_in? %>
                <li><%= link_to "Clients", clients_path  %></li>
                <li><%= link_to "Cars", cars_path  %></li>
                <li><%= link_to "Requets", requests_path  %></li>
                <li><%= link_to "Sales", sales_path  %></li>
                <li><%= link_to "Deals", deals_path  %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to "Clients", clients_path  %></li>
                <li><%= link_to "Cars", cars_path  %></li>
                <li><%= link_to "Requets", requests_path  %></li>
                <li><%= link_to "Sales", sales_path  %></li>
                <li><%= link_to "Deals", deals_path  %></li>
              <% elsif client_signed_in?%>
                <li><%= link_to "Cars", cars_path  %></li>
                <li><%= link_to "Create request", new_request_path  %></li>
                <li><%= link_to "Create sale", new_sale_path  %></li>
              <% else %>
                <li><%= link_to "Cars", cars_path  %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer class="footer">
        <% if admin_signed_in?%>
          <%= link_to "Logout for admin", destroy_session_path(:admin), :method => :delete %>
        <% else %>
          <%= link_to "Login as admin", new_session_path(:admin), :method => :get %>
        <% end %>
        |
        <% if user_signed_in?%>
          <%= link_to "Logout for employee", destroy_session_path(:user), :method => :delete %>
        <% else %>
          <%= link_to "Login as employee", new_session_path(:user), :method => :get %>
        <% end %>
        |
        &copy; Тарнава Кирилл ПО0901
      </footer>

    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>